### ISSUE TITLE
CRUD Service support array modification with $push modifiers

### ISSUE THREAD

**Issue by TheRusCompass** [mia-platform/crud-service#14]
Currently, CRUD service only allows to update (PATCH) an array in documents by adding a single record at a time using `$push` operator.
It would be nice to add the support to `$push` modifiers, such as [`$each`](https://www.mongodb.com/docs/manual/reference/operator/update/each/), [`$position`](https://www.mongodb.com/docs/manual/reference/operator/update/position/), etc... so that those features can be exploited by CRUD service users.
On the contrary, it would be recommended to add a warning banner to CRUD service documentation, so that it is clearly explained that the update interface is only similar and that it does not support all the update operators and modifiers.

**Comment by danibix95** [comment]
Starting from version `v7.2.0` of CRUD Service, it is now possible to use the update modifiers for `$push`, `$addToSet` and `$pull` update commands.

When dealing with array of Objects, please remember to **define the JSON schema** for the object element, so that `PATCH` request validation can properly disambiguate between a `$push`,`$addToSet`,`$pull` of a single element and one with an update modifier (e.g. `{  "field-name": { "$each": [ { "field1": "a-value" } ] } }`) .
