### ISSUE TITLE
The "Local deployment" guideline doesn't work

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/crud-service#27]
Hi guys,
I tried to locally run the `crud-service` following the instructions in the "Local Development" section of the README file.

Just after the repository clone, I run the following commands:
```sh
$ fnm use
Using Node for alias lts-hydrogen

$ node -v
v18.14.0

$ npm -v
9.3.1

$ npm ci

added 569 packages, and audited 732 packages in 6s

63 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


$ docker pull mongo:6.0
6.0: Pulling from library/mongo
Digest: sha256:134e3f2db743d46bdb7f3eb6bcfa4b8e3dde578c9ff8a10742ce29d706acf9b2
Status: Image is up to date for mongo:6.0
docker.io/library/mongo:6.0

$ docker volume create mongo
mongo

$ docker run --detach --name mongo -p 27017:27017 --mount source=mongo,target=/data/db mongo:6.0
be4d4f21fdd4417198d8c0070d96a2d1821cabca175b150824825df5fc18ed1e

$ cp ./default.env ./.env

$ npm run start:local

> @mia-platform/crud-service@6.3.0 start:local
> npm start -- --env-path ./default.env


> @mia-platform/crud-service@6.3.0 start
> lc39 index.js --env-path ./default.env

Error: Cannot find module 'tests/collectionDefinitions/address_statistics.js'
Require stack:
- /Users/frengo/workspace/github/mia-platform/crud-service/index.js
- /Users/frengo/workspace/github/mia-platform/crud-service/node_modules/@mia-platform/lc39/lib/launch-fastify.js
- /Users/frengo/workspace/github/mia-platform/crud-service/node_modules/@mia-platform/lc39/bin/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Array.map (<anonymous>)
    at setupCruds (/Users/frengo/workspace/github/mia-platform/crud-service/index.js:194:6)
    at Plugin.exec (/Users/frengo/workspace/github/mia-platform/crud-service/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/Users/frengo/workspace/github/mia-platform/crud-service/node_modules/avvio/plugin.js:274:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/frengo/workspace/github/mia-platform/crud-service/index.js',
    '/Users/frengo/workspace/github/mia-platform/crud-service/node_modules/@mia-platform/lc39/lib/launch-fastify.js',
    '/Users/frengo/workspace/github/mia-platform/crud-service/node_modules/@mia-platform/lc39/bin/cli.js'
  ]
}

```

I think the common user should be able to clone the repo and run the service just by following the given instructions.
Can you check if I did it wrong?

Moreover, the `cp ./default.env ./.env` is not needed, since the `npm run start:local`command will get the env variables from the `default.env` file.

Thanks guys.

**Comment by danibix95** [comment]
Hi @silversoul93, I believe the problem is in the `default.env` file, where environment variables `COLLECTION_DEFINITION_FOLDER` and `VIEWS_DEFINITION_FOLDER` expect to be a absolute paths.

It is possible to bypass the problem exploiting env variable `$PWD` as shown below:

    COLLECTION_DEFINITION_FOLDER=$PWD/tests/collectionDefinitions

but that would work only in systems supporting such environment.

**Comment by ThisIsDemetrio** [comment]
A couple of personal thoughts. 

It might be true that the `cp ./default.env ./.env` is not needed, because the `npm run start:local` refer to the `default.env` file, but it shouldn't. It should refer to the `.env` file that each user generates, so that the `default.env` file is not modified.

A clarification about the folders used in the `default.env`: these are the folders that the application uses to run tests (executed manually during development and automatically by GitHub Actions) and included there for the sake of running quickly the app, but probably it would be better to have a placeholder and explain that you should generate create your json/js files with the collection definitions. I don't like the risk of having files in source control potentially modified while using the app.

**Comment by danibix95** [comment]
Hi @silversoul93, could you please verify whether this issue has been resolved, so that it is possible to close it?

**Comment by silversoul93** [comment]
> 

@danibix95 I just tried, it works now 💪
