### ISSUE TITLE
GET /count with error in _q returns 500 instead of 400

### ISSUE THREAD

**Issue by GioAc96** [mia-platform/crud-service#55]
**Description**
When querying the `/count` endpoint with a bad value set to the `_q` parameter, the CRUD returns `500` instead of `400`.

**Environment**

I'm using CRUD Service version 4.0.0

**Minimal Reproduction**

Here's the URL I'm using: `http://crud-service/pending-passes/count_q=%7B%22tariff%22%3A13100%7D&_st=PUBLIC%2CDRAFT`
Here's the response I'm getting:
```
{"statusCode":500,"error":"Internal Server Error","message":"Unknown field: tariff"}
```

**Comment by danibix95** [comment]
I would not consider this a bug, but rather an enhancement of the interface. We can work on it to improve CRUD Service interface, but let's keep in mind that it will be a breaking change, since CRUD Service users may have already built a logic considering the current HTTP response.

In the meantime, I would recommend you to upgrade CRUD Service version to the latest one, the `v6.4.0`.
